spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/graphql_test
    username: root
    password: password
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

