spring:
  datasource:
    url: jdbc:mariadb://${DATABASE_HOST:localhost}:3306/graphql_test
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:password}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${DDL_AUTO_TYPE:validate}

