version: '3.9'

services:
  elasticsearch:
    image: elasticsearch:7.8.0
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node

volumes:
  elasticsearch: