version: '3.9'

services:
  mariadb:
    container_name: mariadb
    hostname: mariadb
    image: mariadb:10.7
    ports:
      - 3306:3306
    volumes:
      - ~/apps/mariadb:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=user
      - MYSQL_DATABASE=maria_db
    networks:
    - graphql_test

volumes:
  mariadb:

networks:
  graphql_test:
    external: true
